### ISSUE TITLE
Filters support

### ISSUE THREAD

**Issue by andredasilvapinto** [betfair/cougar#72]
As Cougar doesn't support web.xml Filters, it would be useful to have a replacement mechanism which would let us easily add or remove processors from the request process pipeline (a similar approach is also used in other frameworks like Twitter's Finagle).

The Pre/PostProcessor concept doesn't cover the typical Filter use case as the former is attached to the EV submission and result "pointcuts" and gives access to different structures (e.g. ExecutionContext instead of the Request object).

An architecture with Filters would allow Cougar to more adaptable and configurable, making it easier to integrate framework-wide behaviour (e.g. Tracing or QOS concerns...).

**Comment by eswdd** [comment]
Closing as per various . context resolver in #84 is closest we will get to filters.

**Comment by eswdd** [comment]
Closing as per various . context resolver in #82 is closest we will get to filters.
