### ISSUE TITLE
Implement Zipkin Support

### ISSUE THREAD

**Issue by andredasilvapinto** [betfair/cougar#74]
Implement Zipkin ( http://twitter.github.io/zipkin/ ) support so we can have distributed tracing across all Cougar services inside the same infrastructure.

The implementation should follow Dapper's paper:
http://research.google.com/pubs/pub36356.html

i.e. receive and propagate the trace headers to the underling services when necessary, and emit the relevant spans encapsulating those calls (server received, [client sent, client received]*, server sent).

**Comment by andredasilvapinto** [comment]
So I've just committed a small diff in order to get this started

We need to pick a way to obtain the Zipkin span name (  https://github.com/andredasilvapinto/cougar/commit/b6b82805220f9ee72830225edb3acebc0233b540#diff-af2ffad6565bfb1ed9d44687a022948aR48 ) and we will also need a pointcut when we receive the response from the service we are calling in order to emit the client received annotation.

@eswdd how do you plan on doing this?

**Comment by eswdd** [comment]
i've just committed some changes which include a proper hook in the tracer spi for when a remote call has started. do we need one for when we get the response too?

**Comment by andredasilvapinto** [comment]
Great  and Yes,  that is the one to emit the client received annotation.

**Comment by eswdd** [comment]
Ok will look at that when i do the client calls.

**Comment by andredasilvapinto** [comment]
Just committed the update to the ZipkinTracer and the HttpEmitter. Is this the kind of implementation you are expecting?

**Comment by andredasilvapinto** [comment]
How do you think should be the integration of Zipkin on the Cougar Clients used by non-Cougar applications? 

I think that application should probably start using the ZipkinRequestUUID on its created ExecutionContext instead of the traditional RequestUUID. As ZipkinRequestUUID is compatible with RequestUUID, I guess we can use this approach for every Cougar Client (even though they may refer to old services - e.g. Cougar 2 - with no Zipkin support). Right?

**Comment by eswdd** [comment]
The update to the ZipkinTracer/Emitter looks good, just one thing - would be best to reference the defaultHttpEmitter via the alias exposed in the cougar-client spring config - so we can change the internals if we want.

**Comment by eswdd** [comment]
The clients are interesting. Now that the client automatically creates a sub-uuid from the one passed in (on the assumption that noone ever called in with a new uuid - relatively safe assumption from what I used to see in the logs when I worked at Betfair), we need to make sure this behaviour is obvious when calling a client embedded in non-Cougar apps. Not sure how best to go about this.

Starting with a ZipkinRequestUUID seems sane, if the client has been configured with zipkin (ie the zipkin client module has been loaded) then the client will emit the headers, it would only emit the actual spans if there is a tracer implementation registered.

Clients can receive extra data just fine, so yes, calls to a Cougar 2 service from a Cougar 3 client is perfectly safe.

**Comment by andredasilvapinto** [comment]
> The update to the ZipkinTracer/Emitter looks good, just one thing - would be best to reference the defaultHttpEmitter via the alias exposed in the cougar-client spring config - so we can change the internals if we want.

Fixed.

So now we just need to:
* wire the client send call
* create and wire the new pointcut for the client receive
* test and fix possible bugs
* create unit tests for all of this

I will start by testing the current annotations (server receive and server send). If possible please reply here when you have the pointcuts for the client send and receive, so I can start implementing and testing those too.

**Comment by andredasilvapinto** [comment]
@eswdd I was trying to test Zipkin with a Cougar snapshot version on a Betfair service and I got several compiling errors related with the removed CougarLogger:
https://github.com/betfair/cougar/commit/3af0b414ed31e9d7b116adae51c6d4d4cce9a463

is there a replacement in Cougar for it?

**Comment by eswdd** [comment]
Ok will do. Is nearly there on my laptop, just not had a seat on the train
this week.. :(

**Comment by andredasilvapinto** [comment]
Cool.

I've just remembered that I think we have not decided on the way to mark an entire request chain as "Do Not Trace":

Basically what we discussed here:
https://gist.github.com/eswdd/44aba96d4ce46e89f79a#comment-1284296
https://gist.github.com/eswdd/44aba96d4ce46e89f79a#comment-1297131

Will we pick the new header approach or reuse the old one "X-Trace-Me"?

**Comment by andredasilvapinto** [comment]
@eswdd , not sure if you have seen this, so I'm bumping this again. Should we use "X-Trace-Me" or have a different header to mark an entire request chain as "Do Not Trace"?

**Comment by bfmike** [comment]
Personally I would use something new like X-Trace-Options and then you have somewhere to put other things that might come along in the future..

**Comment by andredasilvapinto** [comment]
So, I found some official documentation from Zipkin (added 10 days ago) which defines the standard headers to be used.

https://github.com/twitter/zipkin/blob/620d4f943fcaa053319e84053cd1a7e1f6332df6/doc/src/sphinx/Instrumenting.rst#communicating-trace-information

We can use other names if we want, as long as they are consisting across the entire infrastructure, but it would be advisable to use those, as they are now standard and used across several other Zipkin implementations (like Finagle, Django, Tryfer-node.js, Go-zipkin...), so I'm changing our headers to the default ones and adding the new:

* X-B3-Sampled: Boolean (either "1" or "0") - "Is Sampled" lets the downstream service know if it should record trace information for the request.

* X-B3-Flags: a Long - "Flags" provide the ability to create and communicate feature flags. This is how we can tell downstream services that this is a "debug" request.

The ids should also be hexadecimally encoded.

**Comment by eswdd** [comment]
Fine with me. The only niggle is the X-Trace-Me which we already use on older Cougar’s.. i suspect we should send both out, or at least send the  X-B3-Sampled from the Zipkin context emitter. On the server, again, I suspect we should handle both to drive the ExecutionContext for compatibility with non-Zipkin tracing.

**Comment by eswdd** [comment]
BTW have just pushed the latest client code. Unit tests not done yet, but I wanted to expose the api changes so you can update your code.
Simon

**Comment by andredasilvapinto** [comment]
OK. Will do tomorrow. Thanks

**Comment by andredasilvapinto** [comment]
Regarding the X-Trace-Me, I understand you want to keep it, but should it be independent from Zipkin? I think in our current architecture it probably makes sense to be so, as it is created and dealt with at a different layer than Zipkin. For instance, HttpContextEmitter already adds the X-Trace-Me header by itself, I don't think Zipkin should interfere with that.

**Comment by andredasilvapinto** [comment]
I've changed the ZipkinEmitter a bit in order to support binary annotations emission (i.e. key-value pairs). I've created methods for the Zipkin supported types of values: boolean, short, int, long, double, String.

I've also added the wiring for the client receive emissions.

Today, I will continue integrating the SNAPSHOT version into a Betfair service.

**Comment by eswdd** [comment]
Cool

**Comment by andredasilvapinto** [comment]
Just wanted to share some of the first Zipkin spans emitted from a Cougar service:
![a](http://i.imgur.com/RYevIZ0.png)

:)

During the tests I've noticed that exceptions in the Zipkin classes break the request. I don't think this is desirable. We should just lose the Zipkin functionality. My question is, should the exception handling be done on the "generic Cougar" side (and apply e.g. to all ContextEmitters) or inside Zipkin. I think it should probably be done inside each Emitter/ComponentResolver, as some of those concrete classes may really want to break the entire request if they fail.

Also, in order to avoid exceptions on RequestUUIDs created manually by non-RPC originated tasks (e.g. background jobs) that use Cougar clients, I have replaced the exceptions that were being triggered on [ZipkinHttpContextEmitter](https://github.com/andredasilvapinto/cougar/commit/6752e720fbf511e49bbdc59d08ea0a44c5bae645#diff-af2ffad6565bfb1ed9d44687a022948aL49) and [ZipkinTracer](https://github.com/andredasilvapinto/cougar/commit/6752e720fbf511e49bbdc59d08ea0a44c5bae645#diff-fc0b7318bf729cc3ce7768f77bf54915L102) when we received a non ZipkinRequestUUID, by a null return or simply ignoring the call. If we want to keep the exceptions we will have to force all background jobs to use ZipkinRequestUUIDs.

Finally I've also moved the localhost ip definition from ZipkinEmitter static initializer to the [XML bean construction](https://github.com/andredasilvapinto/cougar/commit/6752e720fbf511e49bbdc59d08ea0a44c5bae645#diff-6f76f58127cb3fe09ad6dac6c4b46ff6R21) so the class becomes entirely Cougar independent (it is just a wrapper around Brave).

**Comment by eswdd** [comment]
Agree with your comments entirely. Looks good!

**Comment by eswdd** [comment]
Hiya
How're you getting on? I would like to do a release candidate soon. Are you nearly ready to merge?

**Comment by andredasilvapinto** [comment]
Even though I've already successfully tested the implementation in a Cougar
service, I wasn't yet able to make the unit tests as I've being integrating
the new Cougar clients in one of our closed-source platforms (Mantis) in
order to have the client send/receive annotations. This is proving more
difficult than I thought because I need to migrate all the clients and
dependencies from Cougar 2 to 3: several tests broke (with -> set on DTOs,
collections now need to be explicitly declared, packages have changed,
Jackson has changed), some idds are not cougar 3 compatible (errors like
having a field message on an Exception), and we also have 2 cougar helper
libraries that I will need to make sure they are compatible with cougar 3.

As this is a closed-source platform, which I will lose access after
leaving, I'm trying to do as much as possible there. I'm planing on
finishing the Cougar implementation after. Some of my free time is also
going to meetings, interviews and recruiter calls so I've not been able to
do as much with it.

**Comment by andredasilvapinto** [comment]
Still regrading the above message:

Is there an alternative in Cougar 3 to the Cougar 2 method of obtaining access to the transport metrics of a service by using the execution venue object and the operation key of a service:

```
serviceRegisterableExecutionVenue.getExecutable(key).getTransportMetrics()
```

In Cougar 3 there is no getExecutable method.

This is needed for our Circuit Breaker implementation.

**Comment by andredasilvapinto** [comment]
So, I've tried a different approach (uglier but much easier and quicker than upgrading everything to Cougar 3 - there is also some code and other libraries that are depending on Jetty 7 constructions) in order to have this feature on Mantis. I've used AOP around the ExecutionVenue.execute method of Cougar 2 clients, wrapped the Observer for client receive emissions (I thought about using the pre/post processors but, as we know there is no easy way of propagating the Zipkin data from the pre to the post processor) and used the IdentityTokens in order to append the headers to the HTTP request (this is probably the ugliest part as the IdentityChainImpl has protected methods and I had to create a proxy class on its package).

So basically it is working, but it is an hack. If Betfair wants to keep evolving Mantis, the best solution would be to upgrade the clients to Cougar 3 with all the work that would imply. It would take a while, but that kind of work would be necessary in any case when upgrading Jetty or Jackson to their current versions. Jetty 7 is a blatant case, as it was even already deprecated by their maintainers at the end of last year. There is simply no open-source support now and if Betfair doesn't want to be in a fragile position when the next bugs or security problems come out, it should start to seriously consider upgrading to Jetty 9 (8 is also deprecated!).

https://webtide.com/jetty-7-and-jetty-8-end-of-life/

On a different note, I've just noticed that even though we discussed how we could obtain the port of an HTTP request on the protocol's resolver class, we still didn't solve that same question for the Socket protocol. Should we just use cougar.socket.serverport property?

**Comment by eswdd** [comment]
Yuck but i understand. Yes, for socket its safe as secure and insecure run
on the same port (we use a starttls mechanism) so you dont have to be
working out which it arrived on at runtime

**Comment by eswdd** [comment]
Just noticed this. Will look into why it was removed and see about
reinstating.

**Comment by andredasilvapinto** [comment]
So this is SSW (with the Mantis hack) running on my machine and pointing to a Cougar 3 with Zipkin SEAS instance also running on my machine:

![Zipkin trace](http://i.imgur.com/ytzyeAq.png)

The light blue lines are part of SEAS RPCs (in this case is just one to Facet). If all the services were using Zipkin, we would have something like that, but for all the lines (and the RPCs of those endpoints, and the RPCs of the endpoints of those RPCs...).

**Comment by eswdd** [comment]
Looks great. Zipkin porn!:)

**Comment by eswdd** [comment]
So this is all now merged in. I'm still waiting (I think) for gist doco.

Still not massively happy with module structure. Currently using zipkin in client forces inclusion of server side transports. Also config deps mean you can't include without socket or jetty transports. I think I'll break these out to seperate issues to be resolved before release.
