### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by jorgemsrs** [betfair/cougar#87]
Cougar as a modern RPC machine should support CORS out of the box.

CORS stands for Cross-site HTTP requests and relates to the ability to interact with cross domain resources in a safe and standardised way. Our existing web apps are currently using data frames to do cross domain requests which is an insecure and hacky way to solve the problem. jsonp is insecure and clunky as well. cors is the modern and safe way to allow cross domain exchanges.

Additional references:

 - https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
 - http://www.w3.org/TR/cors/

**Comment by eswdd** [comment]
All merged and tests passing.
