### ISSUE TITLE
Deprecate dataframe now we have cors

### ISSUE THREAD

**Issue by eswdd** [betfair/cougar#96]
Documentation mostly although we should investigate adding a setting and defaulting to disabled?

**Comment by jorgemsrs** [comment]
IMHO that's the best option at the moment.
I'd remove it in a major release to allow customers to adapt in the meantime.

**Comment by eswdd** [comment]
Yeah. Wouldnt remove that in a point release..

**Comment by eswdd** [comment]
Not actually a part of cougar - appears my memory is playing up..
